['/fc-test']
to = '/search'
client = 'fc://search'

['/search']
client = 'fc://search'

['/http-test']
target = 'http://gateway.smoex.com/'

# ['/push']
# to = '/push'
# target = 'http://gateway.smoex.com/'